authentication/urls.py
from django.urls import path
from . import views

app_name='authentication'
urlpatterns = [
    path('login/',views.logIn, name='login'),
    path('profile/',views.profileComfirm, name='profile_comfirm'),
    path('api/profile/',views.getProfile, name='profile'),
    path('logout/',views.logOut, name='logout'),
    path('edit/',views.editProfile, name='edit'),
]

crawlr_web/urls.py
from django.urls import path,include,re_path
from authentication.views import linkedInTokenHandle,homepage
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/',include('authentication.urls',namespace='auth')),
    path('ques/',include('question.urls',namespace='ques')),
    path('search/',include('search.urls',namespace='search')),
    re_path('login/',linkedInTokenHandle),
    path('',homepage,name="homepage")
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('result/',views.resultpage,name='result'),
    path('cancel/',views.cancelSearch,name='cancel'),
    path('resultall/',views.resultallpage,name='resultall'),
    path('all/',views.allSearch,name='all'),
    path('api/result/',views.ResultApi,name='result_api')
]

authentication/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import redirect, render
import requests as re
from crawlr_web import settings
import json
from crawlr_web.decorators import login_required


@login_required
def homepage(request):
    return render(request, 'index.html')


def logIn(request):
    if 'jwt_token' in request.session:
        headers = {'content-type': 'application/json',
                   'authorization': request.session['jwt_token']}
        url = settings.API_URL+'/auth/test'
        responce = re.post(url, headers=headers)
        if responce.status_code == 200:
            return redirect('homepage')
        return render(request, 'login.html')
    return render(request, 'login.html')


def logOut(request):
    try:
        del request.session['jwt_token']
        del request.session['UserID']
    except KeyError:
        pass
    return redirect('auth:login')


def linkedInTokenHandle(request):
    code = request.GET.get('code')
    state = request.GET.get('state')
    accessToken = '?code='+code+'&state='+state
    responce = re.post(settings.API_URL+'/auth/linkedin/callback/'+accessToken)
    if responce.status_code == 200:
        jwt_token = responce.json()
        if 'JWT' in jwt_token.keys():
            token = jwt_token['JWT']
            UserID = jwt_token['UserID']
            request.session['jwt_token'] = token
            request.session['user_id'] = UserID
            return redirect('homepage')
        else:
            return render(request, 'profile_comfirmation.html', {'jwt_token': jwt_token})
    return redirect('auth:login')


def profileComfirm(request):
    if request.method == 'POST':
        provider = request.POST.get('provider')
        id = request.POST.get('id')
        fullName = request.POST.get('fullName')
        email = request.POST.get('email')
        image = request.POST.get('image')
        data = {'provider': provider, 'id': id,
                'fullName': fullName, 'image': image, 'email': email}
        headers = {'content-type': 'application/json'}
        responce = re.post(settings.API_URL+'/auth/confirm',
                           data=json.dumps(data), headers=headers)
        if responce.status_code == 200:
            jwt_token = responce.json()
            if 'JWT' in jwt_token.keys():
                token = jwt_token['JWT']
                UserID = jwt_token['UserID']
                request.session['jwt_token'] = token
                request.session['user_id'] = UserID
                headers = {'content-type': 'application/json',
                           'authorization': token}
                url = settings.API_URL+'/auth/test'
                responce = re.post(url, headers=headers)
                return redirect('homepage')
            else:
                raise Http404('something went wrong')
        if responce.status_code == 401:
            return render(request, 'profile_comfirmation.html', {'jwt_token': data, 'error': 'Please give Valid Data'})
        return redirect('auth:login')
    raise Http404('something went wrong try to login again')


@login_required
def getProfile(request):
    if request.is_ajax():
        try:
            responce = re.get(settings.API_URL+'/user', headers={
                              'authorization': request.session['jwt_token'], 'uid': request.session['user_id']})
        except Exception as e:
            print(e)
            return HttpResponse(json.dumps({'status': 500}))
        data = responce.json()
        if responce.status_code == 200:
            return HttpResponse(json.dumps({
                "status": 200,
                "image": data['image'],
                "fullName": data['fullName'],
                "questions": data['questions'],
                "searches": len(data['searches']),
                "karma": data['karma'],
                "email": data['email'],
                "bio": data['bio'],
                "isPremiumUser": data['isPremiumUser']
            }))
        else:
            return HttpResponse(json.dumps({'status': 500}))
    return HttpResponse(json.dumps({'status': 500}))

@login_required
def editProfile(request):
    return HttpResponse('sdf')

authentication/templates/login.html
{%extends 'base_without_navbar.html'%}
{% load static %}
{%block content%}
<style>
  body {
    background-image:url("{%  static "Images/bg1.png" %}");
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    font-family: 'Quicksand';
    font-size: 100%;
    overflow: hidden;
  }

  .bt1 {
    background-color: white;
    border: none;
    padding: 6px 21px;
    text-align: center;
    font-size: 24px;
    border-radius: 10px;
  }

  .text-responsive {
    margin-top: 2rem;
    margin-left: 8rem;
    font-size: calc(100% + 6vw + 6vh);
    font-family: 'Quicksand';
  }

  .text-button {
    font-size: calc(30% + 1vw + 1vh);
    font-family: 'Quicksand';
  }

  .vertical-bottom {
    position: absolute;
    margin-left: auto;
    margin-right: auto;
    left: 0;
    right: 0;
    top: 60vh;
    height: 100vh;
  }
</style>
<h1 class="text-responsive" align="left">crawlr</h1>
<div align="center" class="text-center" style="height:80vh;">
  <div class="row text-center vertical-bottom">
    <div class="col-sm-12 mb-3">
      <button class="bt1 text-button" type="submit">
        <a style="text-decoration: none;color: black;" href="https://crawlr-api.herokuapp.com/auth/linkedin">
          <i class="fa fa-linkedin-square" style="color:#2867B2"></i>
          Continue with LinkedIn
        </a>
      </button>
      <p align="center" class="mt-3" style="font-size: 16px;color: black">By continuing, you agree to our <strong>Terms and Conditions</strong></p>
    </div>
  </div>
</div>
{%endblock%}

authentication/templates/profileEdit.html
{%extends 'base_without_navbar.html'%}
{% load static %}
{%block content%}
<style>
  body {
    font-family: 'Quicksand';
    font-size: 100%;
      background-color : white;
  }

  .bt {
    background-color: #82CAFA;
    border: none;
    border-radius: 50%;
    font-size: 26px;
  }

  .text-responsive {
    font-size: calc(100% + 1.3vw + 1.3vh);
    font-family: 'Quicksand';
  }

  .form-control {
    border-radius: 14px;
    border: none;
    border-bottom: 1px solid #E0E0E0;
    box-shadow: 0 1px 5px -2px rgba(0, 0, 0, .2);

    &:focus {
      box-shadow: 0 1px 5px -2px #42A5F5;
      border-bottom: 1px solid #2196F3;
    }
</style>
<div align="center">
    <div class="row mt-5">
        <div class="col-sm-12"></div>
    </div>
  <div class="row mt-5 mb-2">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <img class=" rounded-circle z-depth-2" src="{{jwt_token.image}}" width="120" height="120">
    </div>
    <div class="col-sm-4"></div>
  </div>
  <p class="text-responsive mb-3" style="display:inline;">Welcome </p>
  <h3 style="display:inline;font-size:40px;font-weight: 700">{{jwt_token.fullName}}</h3>
  <h3 style="display:inline;font-size:34px;">!&nbsp<img src={%  static "Images/prty1.png" %} /></h3>
  <p style="font-size:28px;color:#565A54;" class="mt-4">Confirm your details for us!</p>
  <div style="position:relative; left:5px;width: 320px;text-align: left" class="mb-5 mt-4">
    <form class="form-group mr-2" action="{% url 'authentication:profile_comfirm'%}" method="post">
      {%csrf_token%}
      <input id="id_provider" type="hidden" name="provider" value="{{jwt_token.provider}}">
      <input id="id_id" type="hidden" name="id" value="{{jwt_token.id}}">
      <input id="id_image" type="hidden" name="image" src="{{jwt_token.image}}">
      <div class="mb-4">
        <label for="exampleInputName"><strong>Name</strong></label>
        <input type="text" class="form-control" name="fullName" id="id_fullName" placeholder="Enter your name"
          value="{{jwt_token.fullName}}">
      </div>
      <div>
        <label for="exampleInputEmail"><strong>Email</strong></label>
        <input type="email" class="form-control" name="email" id="id_email" placeholder="Enter your email"
          value="{{jwt_token.email}}">
      </div>
        <div class="row mt-5"></div>
        <div align="center" class="col-sm-12">
             <button type="submit" class="btn btn-info btn-lg bt">Go</button>
        </div>
    </form>
  </div>
</div>
{%endblock%}

authentication/templates/profile_comfirmation.html
{%extends 'base_without_navbar.html'%}
{% load static %}
{%block content%}
<style>
  body {
    font-family: 'Quicksand';
    font-size: 100%;
      background-color : white;
  }

  .bt {
    background-color: #82CAFA;
    border: none;
    border-radius: 50%;
    font-size: 26px;
  }

  .text-responsive {
    font-size: calc(100% + 1.3vw + 1.3vh);
    font-family: 'Quicksand';
  }

  .form-control {
    border-radius: 14px;
    border: none;
    border-bottom: 1px solid #E0E0E0;
    box-shadow: 0 1px 5px -2px rgba(0, 0, 0, .2);

    &:focus {
      box-shadow: 0 1px 5px -2px #42A5F5;
      border-bottom: 1px solid #2196F3;
    }
</style>
<div align="center">
    <div class="row mt-5">
        <div class="col-sm-12"></div>
    </div>
  <div class="row mt-5 mb-2">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <img class=" rounded-circle z-depth-2" src="{{jwt_token.image}}" width="120" height="120">
    </div>
    <div class="col-sm-4"></div>
  </div>
  <p class="text-responsive mb-3" style="display:inline;">Welcome </p>
  <h3 style="display:inline;font-size:40px;font-weight: 700">{{jwt_token.fullName}}</h3>
  <h3 style="display:inline;font-size:34px;">!&nbsp<img src={%  static "Images/prty1.png" %} /></h3>
  <p style="font-size:28px;color:#565A54;" class="mt-4">Confirm your details for us!</p>
  <div style="position:relative; left:5px;width: 320px;text-align: left" class="mb-5 mt-4">
    <form class="form-group mr-2" action="{% url 'authentication:profile_comfirm'%}" method="post">
      {%csrf_token%}
      <input id="id_provider" type="hidden" name="provider" value="{{jwt_token.provider}}">
      <input id="id_id" type="hidden" name="id" value="{{jwt_token.id}}">
      <input id="id_image" type="hidden" name="image" src="{{jwt_token.image}}">
      <div class="mb-4">
        <label for="exampleInputName"><strong>Name</strong></label>
        <input type="text" class="form-control" name="fullName" id="id_fullName" placeholder="Enter your name"
          value="{{jwt_token.fullName}}">
      </div>
      <div>
        <label for="exampleInputEmail"><strong>Email</strong></label>
        <input type="email" class="form-control" name="email" id="id_email" placeholder="Enter your email"
          value="{{jwt_token.email}}">
      </div>
        <div class="row mt-5"></div>
        <div align="center" class="col-sm-12">
             <button type="submit" class="btn btn-info btn-lg bt">Go</button>
        </div>
    </form>
  </div>
</div>
{%endblock%}