crawlr_web/urls.py
from django.urls import path,include,re_path
from authentication.views import linkedInTokenHandle,homepage
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/',include('authentication.urls',namespace='auth')),
    path('ques/',include('question.urls',namespace='ques')),
    path('search/',include('search.urls',namespace='search')),
    re_path('login/',linkedInTokenHandle),
    path('',homepage,name="homepage")
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

question/urls.py
from django.urls import path,re_path
from . import views

app_name = 'question'
urlpatterns = [
    path('pay/', views.payment, name='payment_api'), 
    path('payment_Success/', views.payment_success, name='payment_Success'),
    path('api/post',views.QuestionPost,name="post_api"),
    path('api/postreply',views.ApiReplyPost,name="reply_post_api"),
    path('api/deletereply',views.ApiReplyDelete,name="reply_delete_api"),
    path('api/verifyreply',views.ApiReplyVerify,name="reply_verify_api"),
    re_path('reply/(?P<question>\w+)/',views.ReplyPost,name="reply"),
    re_path('delete/(?P<question>\w+)/',views.DeleteQuestion,name="delete_ques"),
    re_path('all/',views.QuestionList,name="all"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('result/',views.resultpage,name='result'),
    path('cancel/',views.cancelSearch,name='cancel'),
    path('resultall/',views.resultallpage,name='resultall'),
    path('all/',views.allSearch,name='all'),
    path('api/result/',views.ResultApi,name='result_api')
]

question/views.py
from django.shortcuts import render, redirect
from crawlr_web.decorators import login_required
from django.http import HttpResponse, Http404
import requests as re
from crawlr_web import settings
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages


@login_required
def payment(request):
    return render(request, 'payment.html')

@login_required
def payment_success(request):
    razorpay_payment_id = request.POST.get('razorpay_payment_id')
    headers = {'content-type': 'application/json','authorization': request.session.get('jwt_token')}
    try:
        response = re.post(settings.API_URL + '/user', data=json.dumps({'paymentID': razorpay_payment_id}), headers=headers)
    except Exception as e:
        print(e)
        return HttpResponse(json.dumps({'status': 500}))
    return redirect('/auth/login')

@login_required
def QuestionList(request):
    headers = {'content-type': 'application/json','authorization': request.session.get('jwt_token')}
    data1 = {}
    pageNo = request.GET.get('page')
    if pageNo == None:
        pageNo = 1
    else:
        pageNo = int(pageNo)
    if pageNo < 0 or pageNo == 0:
        pageNo = 1
    if pageNo == 1:
        try:
            responce = re.get(settings.API_URL+'/trending')
        except Exception as e:
            print(e)
            raise Http404('something went wrong')
        data1 = responce.json()
    params = {'pageNo': pageNo}
    try:
        responce = re.get(settings.API_URL + '/question/all',params=params, headers=headers)
    except re.ConnectionError as e:
        raise Http404('Check internet connection')
    except re.Timeout as e:
        raise Http404('Connection Timeout')
    except re.RequestException as e:
        raise Http404('Something went wrong')
    except KeyboardInterrupt:
        raise Http404('Someone closed the program')
    if responce.status_code == 200:
        json_res = responce.json()
        data = json_res['data']
        if data:
            pageNo += 1
            next = True
        else:
            next = False
        return render(request, 'question.html', {'trending':data1,'question': data, 'pageNo': pageNo, 'next': next, 'user': request.session['user_id']})
    if responce.status_code == 401:
        return redirect('auth:login')
    raise Http404('some error occurred')
    # return render(request,'question.html',{'question':'spdofsdopf','pageNo':0,'next':False})

@login_required
def DeleteQuestion(request,question):
    headers = {'content-type': 'application/json','authorization': request.session.get('jwt_token')}
    params = {'QuestionID': question}
    try:
        responce = re.delete(settings.API_URL+'/question?QuestionID='+question,data=json.dumps(params),headers=headers)
    except Exception as e:
        print(e)
        raise Http404('someting went wrong ')
    if responce.status_code == 401:
        return redirect('auth:login')
    if responce.status_code == 200:
        messages.success(request, 'your question successfully deleted !', extra_tags='alert alert-info')
        return redirect('ques:all')
    raise Http404('something went wrong')

@login_required
def ReplyPost(request, question):
    pageNo = request.GET.get('page')
    question_text = request.GET.get('question')
    asker = request.GET.get('asker')
    if pageNo == None:
        pageNo = 1
    else:
        pageNo = int(pageNo)
    if pageNo < 0 or pageNo == 0:
        pageNo = 1
    headers = {'content-type': 'application/json','authorization': request.session.get('jwt_token')}
    params = {'pageNo': pageNo, 'questionID': question}
    try:
        responce = re.get(settings.API_URL + '/reply',params=params, headers=headers)
    except Exception as r:
        print(r)
        raise Http404('something went wring')
    if responce.status_code == 200:
        json_res = responce.json()
        data = json_res['data']
        if data:
            pageNo += 1
            next = True
        else:
            next = False
        return render(request, 'reply.html', {'asker':asker,'question': question_text,'question_id':question, 'reply': data, 'pageNo': pageNo, 'next': next, 'user': request.session['user_id']})

    if responce.status_code == 401:
        return redirect('auth:login')
    raise Http404('something went wrong')
    # return render(request, 'reply.html', {'question': '', 'reply': '', 'pageNo': '', 'next': False, 'user': request.session.get('UserID')})


@login_required
@csrf_exempt
def QuestionPost(request):
    if request.is_ajax():
        question = request.POST['question']
        if len(question) == 0:
            messages.error(request, 'your question area is empty',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
        try:
            responce = re.post(settings.API_URL + '/question', data={'question': question}, headers={'authorization': request.session['jwt_token']})
        except Exception as e:
            print(e)
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
        if responce.status_code == 200:
            messages.success(request, 'your question successfully added!', extra_tags='alert alert-info')
            return HttpResponse(json.dumps({'status': 200}))
        else:
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
    messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
    return HttpResponse(json.dumps({'status': 500}))

@login_required
@csrf_exempt
def ApiReplyPost(request):
    if request.is_ajax():
        question = request.POST['questionid']
        reply = request.POST['reply']
        try:
            responce = re.post(settings.API_URL + '/reply', data={'QuestionID': question,'reply':reply}, headers={'authorization': request.session['jwt_token']})
        except Exception as e:
            print(e)
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
        if responce.status_code == 200:
            messages.success(request, 'your reply successfully added!', extra_tags='alert alert-info')
            return HttpResponse(json.dumps({'status': 200}))
        else:
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
    messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
    return HttpResponse(json.dumps({'status': 500}))

@login_required
@csrf_exempt
def ApiReplyDelete(request):
    if request.is_ajax():
        question = request.POST['question']
        id = request.POST['id']
        try:
            responce = re.delete(settings.API_URL + '/reply?QuestionID='+question+'&ReplyID='+id, headers={'authorization': request.session['jwt_token']})
        except Exception as e:
            print(e)
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
        if responce.status_code == 200:
            messages.success(request, 'your reply successfully deleted!', extra_tags='alert alert-info')
            return HttpResponse(json.dumps({'status': 200}))
        else:
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
    messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
    return HttpResponse(json.dumps({'status': 500}))

@login_required
@csrf_exempt
def ApiReplyVerify(request):
    if request.is_ajax():
        question = request.POST['question']
        id = request.POST['id']
        params = {'QuestionID':question,'ReplyID':id}
        try:
            responce = re.post(settings.API_URL + '/reply/verify',data=params,headers={'authorization': request.session['jwt_token']})
        except Exception as e:
            print(e)
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
        if responce.status_code == 200:
            messages.success(request, 'your reply successfully verified!', extra_tags='alert alert-info')
            return HttpResponse(json.dumps({'status': 200}))
        else:
            messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
            return HttpResponse(json.dumps({'status': 500}))
    messages.error(request, 'some error occurred',extra_tags='alert alert-danger')
    return HttpResponse(json.dumps({'status': 500}))

question/templates/question.html
{%extends 'base.html'%}
{%load static%}

{%block title%}Questions{%endblock%}
{%block content%}
<style>
  body {
    font-family: Quicksand;
    background-color: #F0F0F0;
  }

  .button1 {
    background-color: #F0F0F0;
    border: none;
    outline: none !important;
    font-size: 22px;
    cursor: pointer;
  }

  .dropdown-menu {
    display: none;
    position: absolute;
    background-color: #F8F8F8;
    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
    z-index: 1;
    border-radius: 14px;
  }

  .dropdown-item:active {
    background: lightblue;
  }

  .dropdown-item:hover {
    background: lightblue;
  }

  .plusbtn {
    background-color: #F0F0F0;
    border: none;
    border-radius: 50%;
    outline: none !important;
  }

  .border {
    width: 100%;
    border: 1px solid #E8E8E8;
    -webkit-border-radius: 7px;
    -moz-border-radius: 7px;
    border-radius: 7px;

    -webkit-box-shadow: 0px 0px 7px #E8E8E8;
    -moz-box-shadow: 0px 0px 7px #E8E8E8;
    box-shadow: 0px 0px 7px #E8E8E8;
  }
</style>
<!-- Message -->
<div class="row">
  <div class="col-sm-12">
    {% if messages %}
    <ul class="info">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="alert" id="mesaage" style="display:None"></div>
  </div>
</div>

<!-- Button trigger modal -->

<!-- Add Question Popup -->
<div class="modal fade" id="Addquestion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Type Your Question Here...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <textarea name="add_question" id="add_question" data-url="{%url 'ques:post_api'%}" data-csrf='{{csrf_token}}'
          rows="8" cols="50"></textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="closepopque">Close</button>
        <button type="button" class="btn btn-primary" onclick="postQuestion()">Post</button>
      </div>
    </div>
  </div>
</div>
<div class="row mt-5">
  <div class="col-sm-0"></div>
  <div class="col-sm-8">

    <div align="right" class="mb-5">
      <button type="button" class="plusbtn" data-toggle="modal" data-target="#Addquestion">
        <i class="fa fa-plus-circle" style="font-size:24px;color:#36ce77"></i>
      </button>
    </div>
    <div class="infinite-container mb-5">
      {%for data in question%}
      <div class="infinite-item" data-section='ques'>
        <div class="mt-3">
          <span>
            <img class="rounded-circle z-depth-2" src="{{data.image}}" width="40" height="40">
          </span>
          <span style="font-size: 13px;">
            <span><b>{{data.fullName}}</b></span>
            <span>asks</span>
          </span>
          <span style="float: right">
            {%if user == data.askerID%}
            <div class="dropdown">
              <button class="button1" type="button" data-toggle="dropdown">
                <span style="font-weight:bold">. . .</span>
              </button>
              <div class="dropdown-menu">
                <!-- <a class="dropdown-item" href="#" style="color: black;">
                              <span class="mr-3"><i class="fa fa-edit"></i></span>Reply</a> -->
                <a class="dropdown-item" href="{%url 'ques:delete_ques' data.id%}" style="color: black;">
                  <span class="mr-3"><i class="fa fa-trash" style="color:red;"></i>&nbsp;</span>Delete</a>
              </div>
            </div>
            {%endif%}
          </span>
          <div onclick="location.href='{%url 'ques:reply' data.id%}?question={{data.question}}&asker={{data.askerID}}'"
            style="cursor:pointer" class="ml-5 mt-3" style="font-size: 15px;font-weight: bold">
            {{data.question}}
          </div>
          <div align="right" style="font-size: 13px">
            <span>{{data.replies}}</span>
            <span>replies</span>
            <span class="ml-3"><script  type="text/javascript" >document.write(getTimeSince({{data.timestamp}}))</script></span>
            <span>ago</span>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
    <div class="loading" style="display: none;text-align:center">
      <lottie-player src="https://assets3.lottiefiles.com/datafiles/fPx4vaZrul2Fvg9/data.json" mode="normal" 
        speed="1" style="width:150px; height: 150px;" hover loop autoplay>
      </lottie-player>
    </div>
    {%if next%}
    <a class="infinite-more-link" href="?page={{ pageNo }}"></a>
    {%endif%}
  </div>
  <div class="col-sm-4">
    <div class="row">
      <div class="col-sm-0"></div>
      <div class="col-sm-2"></div>
      <div class="col-sm-10">
        <div class="mb-4 mt-3" style="color: #008081;font-size:30px;text-align: center;">
          Trending
        </div>
        <!-- for trending-->
        {%for data in trending.data%}
        <div class="border mt-2" style="background-color:white;display: block;min-height: 40px;">
          <div class="mt-2" style="font-size: small;display: block;width: 97%;">
            <span>
              &nbsp;&nbsp;{{data.searchQuery}}
            </span>
            <span style="float: right;">
              <i class="fa fa-trophy" style="color: gold;"></i>
              <p style="color:#FFD700;display: inline">{{data.points}}</p>
            </span>
          </div>
        </div>
        {%endfor%}
        <!--  end for loop -->

      </div>
    </div>
  </div>
</div>

{%endblock%}

{%block script%}
<script src="{%static 'js/question.js'%}" charset="utf-8"></script>
{%endblock%}

question/templates/reply.html
{%extends 'base.html'%}
{%load static%}

{%block title%}Reply{%endblock%}
{%block content%}
<style>
  body {
    font-family: Quicksand;
    background-color: #F0F0F0;
  }

  .button1 {
    background-color: deepskyblue;
    border-radius: 20px;
    border: none;
    padding: 4px 25px;
  }

  .dropdown-menu {
    display: none;
    position: absolute;
    background-color: #F8F8F8;
    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
    z-index: 1;
    border-radius: 14px;
  }

  .dropdown-item:active {
    background: lightblue;
  }

  .dropdown-item:hover {
    background: lightblue;
  }

  .button2 {
    background-color: #FFFFFF;
    border: none;
    outline: none !important;
    border-radius: 50%;
    font-size: 22px;
  }

  .line1 {
    border: 1px solid lightgray;
    border-radius: 5px;
  }

  .inrep {
    border-radius: 22px;
    width: 100%;
    border: 1px solid #E8E8E8;
    -webkit-border-radius: 22px;
    -moz-border-radius: 22px;
    -webkit-box-shadow: 0px 0px 10px #E8E8E8;
    -moz-box-shadow: 0px 0px 10px #E8E8E8;
    box-shadow: 0px 0px 10px #E8E8E8;
  }
</style>
<!-- Message -->
<div class="row">
  <div class="col-sm-12">
    {% if messages %}
    <ul class="info">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="alert" id="mesaage" style="display:None"></div>
  </div>
</div>

<div class="row">
  <input type="hidden" name="question" id="questionid" value="{{question_id}}">
</div>
<!-- Reply -->
<div class="row mt-5">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div align="center">
      <h3 style="font-weight: bold;font-size: 23px;">Replies</h3>
    </div>
    <div class="mt-4" style="font-size: 35px;">
      {{question}}
    </div>
   <!-- <div class="mt-3">
            <span>
                <img class="rounded-circle z-depth-2" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(30).jpg" width="40" height="40">
            </span>
            <span style="font-size: 13px;">
                <b>{name}</b>
                <span  class="mt-2" style="font-size: 13px;float:right;">{timestamp} ago</span>
            </span>

        </div>
        -->
    <hr class="line1 mt-4">
    <div class="mb-4">
      <form style="width: 100%;">
        <span class="form-group mt-4">
          <input type="text" name="reply" id="reply_text" class="form-control inrep" placeholder="  Your reply..."
            data-url="{%url 'ques:reply_post_api'%}" data-csrf='{{csrf_token}}'>
        </span>
        <button style="float: right;" type="submit" class="btn btn-primary button1 mt-2"
          onclick="postReply()">Reply</button></span>
        <div style="clear: both"></div>
      </form>
    </div>

    <!--more comments-->
    <input type="hidden" value="{%url 'ques:reply_delete_api'%}" data-csrf={{csrf_token}} id="reply_delete_url">
    <input type="hidden" value="{%url 'ques:reply_verify_api'%}" data-csrf={{csrf_token}} id="reply_verify_url">
    <div class="infinite-container">
      <div id="replyload" style="text-align:center"></div>
      {%for data in reply%}
      <div class="infinite-item">
        <div class="mb-4">
          <div class="card mb-1 inrep" style="border-bottom-right-radius: 0px;">
            <!--verify icon-->
            {%if data.isVerified%}
                <i class="fa fa-check-circle" style="color:green;"></i>
            {%else%}
                <i class="fa fa-check-square-o" style="color:white;margin-left: 15px;"></i>
            {%endif%}
            <div class="card-body" style="font-weight: bold;margin-top: -19px;">
              {{data.reply}}
            </div>
            <!-- verify delete -->
            {% if user == asker or user == data.UserID%}
            <span class="ml-3" style="float: right;margin-top: -23px;">
              <div class="dropdown">
                <button class="button2" type="button" data-toggle="dropdown">
                  <span style="font-weight:bold">. . .</span>
                </button>
                <div class="dropdown-menu">
                  {%if user == asker%}
                  <a class="dropdown-item verify-reply" href="#" style="color: black;" data-reply='{{data.id}}'>
                    <span class="mr-3"><i style="color: green;" class="fa fa-check"></i></span>Verify</a>
                  {%endif%}
                  {%if user == data.UserID%}
                  <a class="dropdown-item delete-reply" href="#" style="color: black;" data-reply='{{data.id}}'>
                    <span class="mr-3"><i class="fa fa-trash" style="color:red;"></i>&nbsp;</span>Delete</a>
                  {%endif%}
                </div>
              </div>
            </span>
            {%endif%}
            <!-- end of verify delete -->
          </div>
          <div>
            <span style="float: right;">
              <span class="mt-2 mr-3" style="font-size: 13px;"><script  type="text/javascript" >document.write(getTimeSince({{data.timestamp}}))</script></span>
              <span>
                <img class="rounded-circle z-depth-2" src="{{data.image}}" width="40" height="40">
              </span>
              <span style="font-size: 13px;">
                <b>{{data.fullName}}</b>
              </span>
            </span>
            <div style="clear: both"></div>
          </div>
        </div>
        <!--end comments-->
      </div>
      {%endfor%}
    </div>
    <div class="loading" style="display: none;text-align:center">
        <lottie-player src="https://assets3.lottiefiles.com/datafiles/fPx4vaZrul2Fvg9/data.json" mode="normal" 
          speed="1" style="width:150px; height: 150px;" hover loop autoplay>
        </lottie-player>
      </div>
    {%if next%}
    <a class="infinite-more-link" href="?page={{ pageNo }}"></a>
    {%endif%}
    <div class="mt-5"></div>
  </div>
  <div class="col-sm-2"></div>

</div>

{%endblock%}
{%block script%}
<script src="{%static 'js/question.js'%}" charset="utf-8"></script>
{%endblock%}