crawlr_web/urls.py
from django.urls import path,include,re_path
from authentication.views import linkedInTokenHandle,homepage
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/',include('authentication.urls',namespace='auth')),
    path('ques/',include('question.urls',namespace='ques')),
    path('search/',include('search.urls',namespace='search')),
    re_path('login/',linkedInTokenHandle),
    path('',homepage,name="homepage")
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('result/',views.resultpage,name='result'),
    path('cancel/',views.cancelSearch,name='cancel'),
    path('resultall/',views.resultallpage,name='resultall'),
    path('all/',views.allSearch,name='all'),
    path('api/result/',views.ResultApi,name='result_api')
]

search/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.shortcuts import reverse
import requests as re
from crawlr_web import settings
import json
from crawlr_web.decorators import login_required

@login_required
def resultallpage(request):
    query = request.GET['q']
    search_text = request.GET['t']
    if query == None:
        return redirect('search:all')
    return render(request,'result.html',{'Question_id':query,'search_query':search_text})

@login_required
def allSearch(request):
    headers = {'content-type': 'application/json','authorization': request.session.get('jwt_token')}
    pageNo = request.GET.get('page')
    if pageNo == None:
        pageNo = 1
    else:
        pageNo = int(pageNo)
    if pageNo < 0 or pageNo == 0:
        pageNo = 1
    try:
        responce = re.get(settings.API_URL+'/search/all',params={'pageNo':pageNo},headers=headers)
    except Exception as e:
        print(e)
        raise Http404('something went wrong')
    if responce.status_code == 200:
        res = responce.json()
        data = res['data']
        for i in data:
            i['id'] = i.pop('_id')
        if data:
            pageNo += 1
            next = True
        else:
            next = False
        return render(request, 'mysearch.html', {'searches':data,'pageNo': pageNo, 'next': next})
    if responce.status_code == 401:
        return redirect('auth:login')
    raise Http404('some error occurred')

@login_required
def resultpage(request):
    query = request.POST['q']
    if len(query) == 0:
        return HttpResponseRedirect(reverse('homepage'))
    try:
        responce = re.post(settings.API_URL+'/search',data=json.dumps({'searchQuery':query}),headers={'authorization':request.session['jwt_token'],'content-type':'application/json'})
    except Exception as e:
        print(e)
        raise Http404('somerthing went wrong')
    if responce.status_code == 200:
        return render(request,'result.html',{'Question_id':responce.json()['id'],'search_query':query})
    if responce.status_code == 401:
        return redirect('auth:login')
    raise Http404('something went wrong')
    # return render(request,'result.html',{'Question_id':'5dd780c85ddf35001749ff73'})


@login_required
def ResultApi(request):
    id = request.GET['id']
    try:
        responce = re.get(settings.API_URL+'/search',params={'searchID':id},headers={'content-type':'application/json','authorization':request.session['jwt_token']})
    except Exception as e:
        print(e)
        return HttpResponse(json.dumps({'code':400}))
    if responce.status_code == 200:
        res = responce.json()
        return HttpResponse(json.dumps(res))
    if responce.status_code == 401:
        return HttpResponse(json.dumps({'code':401}))
    return HttpResponse(json.dumps({'code':400}))


@login_required
def cancelSearch(request):
    id = request.GET['id']
    try:
        responce = re.delete(settings.API_URL+'/search/cancel?id='+str(id),headers={'content-type':'application/json','authorization':request.session['jwt_token']})
    except Exception as e:
        print(e)
        raise Http404('something went wrong')
    if responce.status_code == 200:
        return redirect('search:all')
    if responce.status_code == 401:
        return redirect('auth:login')
    raise Http404('something went wrong')

search/templates/mysearch.html
{%extends 'base.html'%}
{%load static%}

{%block title%}searches{%endblock%}
{%block content%}

    <style>
            body{
                font-family: Quicksand;
                background-color: whitesmoke;
            }
          .border {
            width: 100%;
            border: 1px solid #E8E8E8;
            -webkit-border-radius: 7px;
            -moz-border-radius: 7px;
            border-radius: 7px;

            -webkit-box-shadow: 0px 0px 7px #E8E8E8;
            -moz-box-shadow: 0px 0px 7px #E8E8E8;
            box-shadow: 0px 0px 7px #E8E8E8;
          }
    </style>

<!-- Message -->
<div class="row">
    <div class="col-sm-12">
      {% if messages %}
      <ul class="info">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
      <div class="alert" id="mesaage" style="display:None"></div>
    </div>
  </div>

  <!-- searches -->
    <div align="center">
        <div class="row mt-5">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <div>
                    <h3 style="font-weight: bold;font-size: 23px;">My Searches</h3>
                </div>
                <div class="mt-5">
                    <div class="infinite-container">
                    {%for data in searches%}
                      <!-- bar 1-->
                      <div class="infinite-item">
                        <div class="border mt-2" style="background-color:white;display: block;min-height: 47px;">
                          <div class="mt-2" style="font-size: large;display: block;width: 97%;">
                            <a href="{%url 'search:resultall'%}?q={{data.id}}&t={{data.searchQuery}}" style="color: black;text-decoration:none">
                            <span style="float: left;">
                              &nbsp;&nbsp;{{data.searchQuery}}
                            </span>
                          </a>
                            <span style="float: right;font-size: 22px;margin-top: -4px">
                              {%if data.status == 'D'%}
                             <i class="fa fa-check-circle-o" style="color: limegreen;"></i>
                             {%endif%}
                             {%if data.status == 'ERR'%}
                             <i class="fa fa-times-circle-o" style="color: #F55D45;"></i>
                             {%endif%}
                             {%if data.status == 'C'%}
                              <i class="fa fa-exclamation-triangle" style="color: yellow;"></i>
                              {%endif%}
                              {%if data.status == 'P'%}
                              <span style="float: right;">
                                  <a href="{%url 'search:cancel'%}?id={{data.id}}"
                                     style="font-size: small;color: white;text-decoration:none;"
                                     class="btn btn-lg btz1">
                                      <span>Cancel</span>
                                  </a>
                              </span>
                              {%endif%}
                            </span>
                          </div>
                          </div>
                        </div>  
                    {%endfor%}
                    </div>
                    <div class="loading" style="display: none;text-align:center">
                        <lottie-player src="https://assets3.lottiefiles.com/datafiles/fPx4vaZrul2Fvg9/data.json" mode="normal"
                          speed="1" style="width:150px; height: 150px;" hover loop autoplay>
                        </lottie-player>
                      </div>
                      {%if next%}
                      <a class="infinite-more-link" href="?page={{ pageNo }}"></a>
                      {%endif%}
                </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
{%endblock%}
{%block script%}
<script src="{%static 'js/question.js'%}" charset="utf-8"></script>
{%endblock%}

search/templates/result.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<input type="hidden" name="id" value="{{Question_id}}">
<input type="hidden" name="result_url" value="{%url 'search:result_api'%}">
<!-- MAIN --->
<style>
    body {
        font-family: Quicksand;
        background-color: whitesmoke;
    }

    p {
        margin: 0
    }
</style>
<div class="row mt-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <div align="center">
            <h3 style="font-weight: bold;font-size: 23px;">Search Result</h3>
        </div>
        <div class="mt-5 mb-5">

            <h3 style="font-size: 27px;display: inline;">{{search_query}}</h3>&nbsp;
            <span style="font-size: 26px;" id="querystatus">
               
            </span>
            <div id="data"></div>

        </div>

    </div>
    <div class="col-sm-2"></div>
</div>

{%endblock%}
{%block script%}
<script src="{%static 'js/search.js'%}" charset="utf-8"></script>
{%endblock%}