authentication/urls.py
from django.urls import path
from . import views

app_name='authentication'
urlpatterns = [
    path('login/',views.logIn, name='login'),
    path('profile/',views.profileComfirm, name='profile_comfirm'),
    path('api/profile/',views.getProfile, name='profile'),
    path('logout/',views.logOut, name='logout'),
    path('edit/',views.editProfile, name='edit'),
]

crawlr_web/urls.py
from django.urls import path,include,re_path
from authentication.views import linkedInTokenHandle,homepage
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/',include('authentication.urls',namespace='auth')),
    path('ques/',include('question.urls',namespace='ques')),
    path('search/',include('search.urls',namespace='search')),
    re_path('login/',linkedInTokenHandle),
    path('',homepage,name="homepage")
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

question/urls.py
from django.urls import path,re_path
from . import views

app_name = 'question'
urlpatterns = [
    path('pay/', views.payment, name='payment_api'), 
    path('payment_Success/', views.payment_success, name='payment_Success'),
    path('api/post',views.QuestionPost,name="post_api"),
    path('api/postreply',views.ApiReplyPost,name="reply_post_api"),
    path('api/deletereply',views.ApiReplyDelete,name="reply_delete_api"),
    path('api/verifyreply',views.ApiReplyVerify,name="reply_verify_api"),
    re_path('reply/(?P<question>\w+)/',views.ReplyPost,name="reply"),
    re_path('delete/(?P<question>\w+)/',views.DeleteQuestion,name="delete_ques"),
    re_path('all/',views.QuestionList,name="all"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('result/',views.resultpage,name='result'),
    path('cancel/',views.cancelSearch,name='cancel'),
    path('resultall/',views.resultallpage,name='resultall'),
    path('all/',views.allSearch,name='all'),
    path('api/result/',views.ResultApi,name='result_api')
]

templates/base.html
{%extends 'base_without_navbar.html'%}
{%block navbar%}
{%include 'navbar.html'%}
{%endblock%}

templates/base_without_navbar.html
{%load static%}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>
  <title>{%block title%}{%endblock%}</title>
</head>
<script src="https://unpkg.com/feather-icons"></script>
<body>
    <script src="{%static 'js/getTimeSince.js'%}"></script>
  {%block navbar%}{%endblock%}
  <div class="container">
    <div class="container-fluid">
      {%block content%}{%endblock%}
    </div>
  </div>
  <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  <script src="{%static 'js/jquery-3.1.1.min.js'%}" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="{%static 'js/jquery.waypoints.min.js'%}" charset="utf-8"></script>
  <script src="{%static 'js/infinite.min.js'%}" charset="utf-8"></script>
  <script src="{%static 'js/profile.js'%}"></script>
  <script>
    feather.replace()
  </script>
  {%block script%}{%endblock%}
</body>

</html>

templates/index.html
{%extends 'base.html'%}
{%load static%}

{%block title%}Search{%endblock%}
{%block content%}
<style>
  body {
    background-image:url("{%  static "Images/bg1.png" %}");
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    font-family: 'Quicksand';
    font-size: 100%;
    overflow: hidden;
  }

  .button1 {
    background-color: #F55D45;
    border-radius: 20px;
    border: none;
    padding: 4px 25px;
  }

  .text-responsive {
    font-size: calc(100% + 6vw + 6vh);
    font-family: 'Quicksand';
  }

  .inrep {
    border-radius: 22px;
    width: 100%;
    border: 1px solid #E8E8E8;
    -webkit-border-radius: 22px;
    -moz-border-radius: 22px;
    -webkit-box-shadow: 0px 0px 3px #E8E8E8;
    -moz-box-shadow: 0px 0px 3px #E8E8E8;
    box-shadow: 0px 0px 3px #E8E8E8;
  }
</style>
<div class="row mt-5">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 mt-5">

    <div class="text-responsive mb-5" align="center">
      <h3>Get in-depth info of a <b>domain</b>, </h3>
      <h3>Verify an <b>email address</b> or </h3>
      <h3>Just type in a <b>username!</b> </h3>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="mb-4">
          <form style="width: 100%;" action="{%url 'search:result'%}" method="POST">
            {%csrf_token%}
            <span class="form-group mt-4 ">
              <input type="text" style="height: 42px;" class="form-control inrep" name="q" placeholder="  Search for a domain, email or a username...">
            </span>
            <button style="float: right;" type="submit" class="btn btn-success button1 mt-2">
              <i class="fa fa-search"></i>
              Search
            </button>
            </span>
            <div style="clear: both"></div>
          </form>
        </div>
      </div>
    </div>

  </div>
  <div class="col-sm-2"></div>
  {% endblock %}

templates/navbar.html
{%load static%}
<style>
    body {
        font-family: 'Quicksand';
      }
    .navbar-custom {
        background-color: #197DAF;
    }

    .navbar .dropdown-menu {
        background-color: #F0F0F0;
        width: 310px;
        border-radius: 10px;
    }

    .buttn1 {
        border-radius: 50%;
    }

    .buttn1:focus,
    .buttn1:active {
        outline: none !important;
        box-shadow: none;
    }

    .btn:focus,
    .btn:active {
        outline: none !important;
        box-shadow: none;
    }

    .tr {
        font-size: calc(100% + 0.3vw + 0.3vh);
        font-family: 'Quicksand';
    }

    .btz {
        background-color: gold;
        border-radius: 20px;
        border: none;
        padding: 4px 17px;
    }

    .btz1 {
        background-color: #ff3333;
        border-radius: 20px;
        border: none;
        padding: 4px 20px;
    }

    .acnvb:hover {
        opacity: 3
    }

    .acnvb:hover {
        background-color: #1991d1;
    }
</style>
<nav class="navbar navbar-expand-md navbar-dark navbar-custom" style="height: 47px;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
        <div style="color:white;font-weight: bold;font-size: large;text-shadow: 2px 2px #00ace6;">
            CRAWLR
        </div>
        <ul class="navbar-nav mx-auto">
            <li class="nav-item mr-5 acnvb">
                <a class="nav-link" href="{%url 'homepage'%}" style="color: white;">Home
                </a>
            </li>
            <li class="nav-item mr-5 acnvb">
                <a class="nav-link" href="{% url 'ques:all'%}" style="color: white;">Connect</a>
            </li>
            <li class="nav-item acnvb">
                <a class="nav-link" href="{%url 'search:all'%}" style="color: white;"> My Searches</a>
            </li>
        </ul>
        <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
            <li class="dropdown order-1">
                <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn dropdown-toggle buttn1">
                    <span id="profileimage1">

                    </span>
                    <span style="font-size: small;color:white">
                        <span id="fullname1"></span>
                    </span>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right mt-0">
                    <div class="loading" style="display: block;text-align:center">
                        <lottie-player src="https://assets3.lottiefiles.com/datafiles/fPx4vaZrul2Fvg9/data.json"
                            mode="normal" speed="1" style="width:150px; height: 150px;" hover loop autoplay>
                        </lottie-player>
                    </div>
                    <form id="profileformnavbar" style="display: none;">
                        <li class="x3 px-3 py-2">
                            <div>
                                <div style="text-align: center;">
                                    <p class="tr mb-5" style="display:inline;font-size: small;"><strong>My
                                            Account</strong>
                                    </p>
                                    <div class="mt-5 mb-3" id="profileimage2">
                                        <img src="" alt="" width="80" height="80">
                                    </div>
                                    <p class="mb-1" style="font-size: medium;font-weight: 700;" id="fullname2">{Name
                                        John}
                                    </p>
                                    <p class="mb-3" style="font-size: x-small;" id="email"></p>
                                    <p style="font-size: x-small;font-weight:600;" id="about"></p>
                                </div>
                                <div class="row mt-4" style="text-align: center;">
                                    <div class="col-sm-4">
                                        <div style="font-size: small;font-weight: 600;" id="searches"></div>
                                        <div style="font-size: small">Searches</div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div style="font-size: small;font-weight: 600;" id="questions"></div>
                                        <div style="font-size: small">Questions</div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div style="font-size: small;font-weight: 700;" id="replys"></div>
                                        <div style="font-size: small">Karma</div>
                                    </div>
                                </div>
                                <div class="row mt-5" style="text-align: center;">
                                    <div class="col-sm-6" id="premiumbutton">
                                        <a href=""></a>
                                        <a href="{%url 'ques:payment_api'%}"
                                            style="font-size: small;color: black;text-decoration:none"
                                            class="btn btn-lg btz">

                                            <span><i style="color: black"
                                                    class="fa fa-star-o"></i>&nbsp;Premium</span>&nbsp

                                        </a>
                                    </div>
                                    <div class="col-sm-0"></div>
                                    <div class="col-sm-6">
                                        <a href="{%url 'auth:logout'%}"
                                            style="font-size: small;color: white;text-decoration:none"
                                            class="btn btn-lg btz1">
                                            <span><i class="fa fa-power-off"></i>&nbsp;Log</span>&nbsp<span>out</span>

                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </form>
                </ul>
            </li>
        </ul>
    </div>
    <input type="hidden" id="profileurl" value="{% url 'auth:profile'%}">
</nav>

templates/payment.html
<!-- <button id="rzp-button1">Pay with Razorpay</button>
<input type="number" id="rzp-ammount-input">
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_Brb8XikYT4Alsv", // Enter the Key ID generated from the Dashboard
    "amount": "", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise or INR 500.
    "currency": "INR",
    "name": "Siddhant   ",
    "description": "Razor Pay",
    // "image": "https://example.com/your_logo",
    "order_id": "",//This is a sample Order ID. Create an Order using Orders API. (https://razorpay.com/docs/payment-gateway/orders/integration/#step-1-create-an-order). Refer the Checkout form table given below
    "handler": function (response){
        alert(response.razorpay_payment_id);
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "",
        "contact": "9999999999"
    },
    "notes": {
        "address": "note value"
    },
    "theme": {
        "color": "#F37254"
    }
};
function handleInput(){
    options.amount = document.getElementById('rzp-ammount-input').value;
    console.log(options)
}
document.getElementById('rzp-button1').onclick = function(e){
    handleInput();
    var rzp1 = new Razorpay(options);
    rzp1.open();
    e.preventDefault();
}
</script>
<script>
    Window.onalert()    
</script> -->

<form action="{%url 'ques:payment_Success'%}" method="POST">
  {% csrf_token %}
  <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_Brb8XikYT4Alsv"
    data-amount="50000"
    data-currency="INR"
    data-order_id=""
    data-buttontext="Pay with Razorpay"
    data-name="Crawlr"
    data-description="Prime Subscription"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name=""
    data-prefill.email=""
    data-prefill.contact=""
    data-theme.color="#F37254"
  ></script>
  <input type="hidden" custom="Hidden Element" name="hidden" />
</form>